version: '3'

services:
  geanroot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geanroot
    env_file: .env
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:${PORT}:3000"
    volumes:
      - "${WORKDIR}:/opt/JSAP"
    entrypoint: ["bash"]
